### ISSUE TITLE
Detect using runtime in CMakeLists.txt

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#14]
Is there any way to detect using runtime( `io.js`/`nw.js`/`Electron`) inside CMakeLists.txt?
Thanks in advance.

**Comment by unbornchikken** [comment]
Hello,

0.12 has just released. See: https://github.com/unbornchikken/cmake-js#runtime-options-in-cmakeliststxt.

**Comment by RSATom** [comment]
Thanks!
