### ISSUE TITLE
How to alway use latest `runtimeVersion` ?

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#15]
I don't want declare version directly. Is it possible setup always use the latest version?

something like

    "cmake-js":
    {
        "runtime": "node",
        "runtimeVersion": "*"
    }

Thanks in advance.

**Comment by unbornchikken** [comment]
I is not an obvious way to know which version is the latest. For example, dist repo of electron does't support file listing in http, so you have to HTTP OPTONS all posdible semver combinations to know which one is the latest. We could go with:

'''
node --version
nw --version
'''

etc. on this case though

**Comment by RSATom** [comment]
If I understand all correctly then we will get version of installed `node.js` or `nw.js`, not the latest. Or maybe you mean something else?

**Comment by unbornchikken** [comment]
We get the version of installed runtime I mean.

**Comment by RSATom** [comment]
Now understand.
Unfortunately it will not work if I plan build my addon for deployment to npm. I.e. I will not have any runtime installed at all.

Anyway I understand you. It seems I will have to hardcode runtime versions to my deployment prepare script.

Thanks for your assistance.
