### ISSUE TITLE
Is it possible define runtime/runtimeversion/arch on `npm install`?

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#16]
It has a meaning for developers who start new projects and don't have `package.json` for root project yet or don't have `cmake-js` section in it. And according to docs:

>  If you're creating a native module targeting nw.js for example, then do not specify anything in your module's package.json.

Thanks in advance.

**Comment by unbornchikken** [comment]
Runtime resolution works by the following algorithm:

- CMake.js building process started in some directory (it's separate for each CMake.js modules in the dependency chain)
- It searches for the root package.json file, that means it walks to parent directories, if it's not in the actual directory (node_modules wise) until there is package.json found. If not, then picks the last.
- Are there cmake-js senction?
    - YES: use it's runtime setings to build the target if any
    - NO: use the running runtime's parametes to build the target

So if you create a CMake.js based module, it's not you that have to decide if it installed as NW.js or Node.js application's module. It can be used anywhere in any runtime. So there should be no cmake-js settings in module's package.json file. In thet case you can run your unit tests in node runtime that is available in the commandline, which means entering `mocha tests` will just work.

**Comment by unbornchikken** [comment]
Depite the above automatic process exists, you can be explicit, by using appropriate commandline options of `cmake-js`:

`npm install cmake-js -g
cmake-js --help`

That prints availale options for `build` command:

```
 -r, --runtime          the runtime to use                             [string]

 -v, --runtime-version  the runtime version to use                     [string]

 -a, --arch             the architecture to build in                   [string]
```

So you can specify it in your module's package.json file's install script like:

```
"install": "cmake-js rebuild --runtime=nw --runtime-version=0.12.1 --arch=x64"
```

**Comment by RSATom** [comment]
> NO: use the running runtime's parametes to build the target

The main problem is `nw.js` or `Electron` could not be "running runtime", it could be only `io.js` or `node.js`. So if user want `npm install some_module` for `Electron` or `nw.js` runtime and don't have `cmake-js` section anywhere he have no way to get right binaries of installing module.

**Comment by unbornchikken** [comment]
CMake.js is designed to be runtime agonistics for module developers. So your module's documentation should mentions that there should be `cmake-js` section in package.json. It fair less PITA than they have to use `nw-gyp` like mess, ain't it?

If you specify build options in your module, then you have to have separate modules for NW.js and Elector and for each versions, which will yield a huge ammount of npm packages.

**Comment by unbornchikken** [comment]
If you have an idea to how we could work around this, please tell. I'll implement it ASAP.

**Comment by RSATom** [comment]
> CMake.js is designed to be runtime agonistics for module developers. So your module's documentation should mentions that there should be cmake-js section in package.json. It fair less PITA than they have to use nw-gyp like mess, ain't it?

I'm absolutely agree with that. I just think it will be good have one else way to override defaults, in my case for `npm install`. And it should be done in command line to avoid this: 

> If you specify build options in your module, then you have to have separate modules for NW.js and Elector and for each versions, which will yield a huge ammount of npm packages.

Yes, it's exactly what I want to avoid.

---

Tbh, I already have some idea just don't sure how well it is.
I was thinking about add possibility define runtime/runtimeVersion/arch via `npm config`

**Comment by unbornchikken** [comment]
The problem with regarding `npm config` is that that's global. If you set it then every CMake.js build are gonna built for that. I thing having to have specify 3 lines in packae.json is far cleaner approach.

**Comment by RSATom** [comment]
do you mean if I run

**Comment by RSATom** [comment]
Do you mean if run something like

    config set cmake-js:runtime electron

it will be used for all project that uses cmake-js?

In documentation https://docs.npmjs.com/cli/config mentioned `--global` flag, but unfortunately not described what exactly it mean.

**Comment by unbornchikken** [comment]
It's very basic functionality. Spec chars cannot be used though.

```
config set cmake_js_runtime electron
```

= it creates an .npmrc file in your home, and put: `cmake_js_runtime=electron` in it.

For each npm script execution it defines environment variables of .npmrc, so you will get `process.env.NPMCONFIG_cmake_js_runtime="electron"` or something like this (I'm not sure about the perfix). So every `npm install` will get this, so every `cmake-js rebuild` will get this.

**Comment by RSATom** [comment]
So maybe I still will use `npm config` but only with keys specific only to my addon

    npm config set webchimera:runtime electron

Or maybe will remove default install script and will use [run-script](https://docs.npmjs.com/cli/run-script) since it allow pass arguments.

**Comment by RSATom** [comment]
Thank you for your help, I think this question could be closed.
