### ISSUE TITLE
Feedback: What if I say installing Visual Studio won't required on Windows anymore?

### ISSUE THREAD

**Issue by unbornchikken** [unbornchikken/cmake-js#17]
Hi,

Just gathering feedback on the title. I think I can implement full MinGW toolchain support for Windows. That means Visual Studio (= 12 GBytes hog) won't required to build CMake.js based modules. MinGW could be installed from SourceForge: http://sourceforge.net/projects/mingw-w64/ and a far less PITA than installing Visual Sutdio. But even I can provide a DropBox based automatic install mechanism, which means to use CMake.js build system there should not be anything installed on Windows other than CMake!

My question is, does it worth my effort? Is the requirement of installing Visual Studio a real problem, or you can live with it?

**Comment by RSATom** [comment]
How about create something like `node-pre-gyp`? Building module from sources does not give any benefits to end users. I mean it will be better find way to simplify binaries deployment, than try simplify build sources by end users, since they anyway could meet many other problems except Visual Studio installation...

**Comment by piranna** [comment]
node-pre-gyp is only useful for standard platforms, for not standard ones there will be no other alternatives that building from sources. It makes more sense to simplify first build sources so anyone can install the modules easily, and later simplify binaries deployment to speed up installs.

**Comment by RSATom** [comment]
@piranna, what do you mean by "non standard platforms"?

**Comment by unbornchikken** [comment]
@RSATom I think @piranna meant io.js and company like NW.js and Electron. node-pre-gyp was a good idea in its time, but considering io.js and its release cycle with frequent breaking v8/libuv changes, it could be a heavy burden on  module developers shoulders to provide binraies for each possible platforms and architectures and node/io.js combinations. I really doubt that a hobbyst would ever want to afford his or her time and money to provide all of possible binary combinations. Even the storage isn't free.

Building from source is not a wrong idea. On POSIX (including Mac with Homebrew) this was not and won't ever be a problem. Just Windows is the outlier there with its *you have to pay for MS to create stuff to make their OS more attractive to users to pay for MS to have it* strategy. If it's not required to install 12 GBytes in a half of a hour to have a f..ing MongoDB driver for JavaScript, then we're good, aren't we?

Binary distribution system [is in the works though](https://github.com/distUR/distUR.net), I have an early prototype. The main idea compared to node-pre-gyp is that not only the developer of the module allowed to provide a binary for a module, anyone is. Just register to my service with your dropbox and github account, and if anythhing builds at your side, then it will persist. And the next user on the same platform and runtime will get the binary of yours. Kinda peer-to-peer stuff. Module authors could have badges to show how mutch platforms are covered by its available binaries around the world. Coz everyone loves badges. That's the plan, but to make it work someone somewhere should build the module first from source, so making that process is less PITA should be on the top priority by my opinion.

**Comment by piranna** [comment]
> I think @piranna meant io.js and company like NW.js and Electron.

In fact, I was talking about non-x86 CPUs and "exotic" OSes like FreeBSD or Haiku, that has Node.js support. Distribute modules in binary form will leave this behind, and only alternative is having the sources, that's why I think we should improve efforts on this point.

Think about this fact, I'm the lead developer of NodeOS that don't have a global toolchain installed but instead would be desirable that it becames installed by npm. Ok, C compiler is the first stone and hope llvm.js or something similar could do the trick, but after that, although it's Linux based it uses musl as libc, so the only available way to install compiled modules is compiling them...

**Comment by piranna** [comment]
[OffTopic]

> Binary distribution system is in the works though, I have an early prototype. The main idea compared to node-pre-gyp is that not only the developer of the module allowed to provide a binary for a module, anyone is. Just register to my service with your dropbox and github account, and if anythhing builds at your side, then it will persist. And the next user on the same platform and runtime will get the binary of yours. Kinda peer-to-peer stuff. Module authors could have badges to show how mutch platforms are covered by its available binaries around the world. Coz everyone loves badges. That's the plan, but to make it work someone somewhere should build the module first from source, so making that process to be less PITA should be on the top priority by my opinion.

F*cking interesting idea, I love it! :-D Just one question: how do you prevent people to don't upload binaries with malware inside? If it's a first-come-first-served basis, it could be really easy to distribute viruses in your name, and if there's no previous compilation of that binary in that version in that platform, you can't be able to check their md5 nor be sure that the compiled code it's the same from your repo... Anyway good work, very intelligent trick ;-)

[/OffTopic]

**Comment by unbornchikken** [comment]
Yes malware could be a problem. My idea is that every user should register in the service with Dropbox account for storage, and with Github account for profile. From GH profile we know that how many repos, activities, etc the user has, so we know that how mutch is he or she reliable. On the client you could set security options to allow get binaries from anyone, quite reliable people, strong reliable people,etc. Reliability 'points' cold be improved with how many of your binaries are in use for a certain period of time, it could be achieved with a binding module's fork. Users and modules could be allowed or denied manually at the site. Too many disallowed status for a user with a reason: malware means investigation from admins and ban.

I can get it together in a few monts alone with Meteor. And if it works, maybe I could go to Kickstarter. And I planning to make a node-gyp PR for suppprting this too.

Sorry for the typos, I'm from my cellphone.

**Comment by RSATom** [comment]
>  it could be a heavy burden on module developers shoulders to provide binraies for each possible platforms and architectures and node/io.js combinations.

Absolutely agree with you, and binary distributions should not exclude possibility to build from sources of course. But it's good to have binaries for most popular platforms/engines to not lose lazy developers (most of programmers are lazy, me include ;)

> Building from source is not a wrong idea.

Yes, on linux it's the only right choice.

> On POSIX (including Mac with Homebrew) this was not and won't ever be a problem. 

Mac OS X does not have by default any package mangers (Homebrew or MacPorts) and don't have any developers tools. So it's the same case as with Windows.

>  The main idea compared to node-pre-gyp is that not only the developer of the module allowed to provide a binary for a module, anyone is.

It will be huge security hole, don't think it's good idea.

---

Anyway, approach with downloading gcc toolchain still good idea and I think it could be usefull even on Mac OS X. So I vote up for this.

**Comment by piranna** [comment]
@unbornchikken, I think your authentication mechanism is cumbersome, request too much info to the users (that will make them not use it), needs too much administration and can be cheated since GitHub account can be filled with fake info in just seconds, too. Ideally it should be enough with just one credential, not two of them.

Good idea, but I would rethink the mechanism to validate binaries and make it simpler and more secure, probably there would be alternatives. Maybe developer signatures?

**Comment by unbornchikken** [comment]
@piranna it's just two clicks on the site with oauth, easy as goblin pie. But you're right, my idea is not enough polished right now, that's why I haven't announced it anywhere. The first step is to make the actual registration / upload / download workflow work, then we can discuss about security concerns. I'll get back to you the, because this developer signature idea is really interest me though.

@RSATom I'm pretty noob with Mac. I have a hacked Mac 10.8.5.6.8.4 Mountain Wolverine in VirtualBox and that's it. It was a huge PITA to find the latest Developer Commandline Tools that work with this version indeed, but I believe developer tools could be installed with Homebrew, couldn't be?

**Comment by RSATom** [comment]
in the latest versions Developer Commandline Tools installed with XCode or from XCode via settings dialog. So you have to install some Gb of XCode before you could install Developer Command Lite Tools. So it's identical to Windows with Visual Studio...

**Comment by RSATom** [comment]
It seems it's still possible install Command line tools without XCode: http://www.cnet.com/how-to/install-command-line-developer-tools-in-os-x/
But I never tried this.

**Comment by RSATom** [comment]
> I believe developer tools could be installed with Homebrew, couldn't be?

I think yes, it could, but I never tried it too.

**Comment by unbornchikken** [comment]
Yeah, on paper. :) Instead I had this (as a noob):

- Mac installed 
- Xcode downloaded, installation started
- Installation halted w/ error, 10.8.5.6.8.4 Mountain Wolverine is not supported by this version of Xcode
- Google
- Apple Dev Center, many - many older Xcode versions available, at least 5 of them for 10.8 according to descriptions. Ok, download the latest for 10.8
- Xcode downloaded, installation started
- Installation halted w/ error, 10.8.5.6.8.4 Mountain Wolverine is not supported by this version of Xcode it for above 10.8.7.
- Download the oldest
- Xcode downloaded, installation started
- Ok, I have an old Xcode. Goto its menu, Download and install CL Tools. It's halted with a cryptic error message.
- Ok, gotta download the commandline tools only form Apple Dev Center, many - many older CL Tools versions available, at least 5 of them for 10.8 according to descriptions, but there are event ones without any mention of the actual OSX version in descriptions. Ok, download the latest for 10.8
....

It took me 3 hours to get a f..ing Clang 3.4 working. 3.4!

**Comment by RSATom** [comment]
I'm not surprised, since Apple don't support old dev tools too long. If take in to account latest Mac OS X and XCode versions  are free to download (on official Macs of course) - it has a meaning. Just to keep most of the users updated to the latest versions.

**Comment by RSATom** [comment]
anyway, it's just prove that possibility to install build toolchain on build - is good idea. but maybe it's not necessary do it inside cmake-js, maybe just as npm package? And then we could add it just as dependency.

**Comment by piranna** [comment]
> anyway, it's just prove that possibility to install build toolchain on build - is good idea. but maybe it's not necessary do it inside cmake-js, maybe just as npm package? And then we could add it just as dependency.

On NodeOS I have build the cross-toolchain as a npm package, although I've not moved it out yet due to limitations of npm itself. For npm 3 with multi-stage installs and flat dependencies it should work when gets released :-)

**Comment by RSATom** [comment]
@piranna, it's very interesting, what npm limitations did you met? and what is "multi-stage installs" and "flat dependencies". Sorry if it's dumb question -I'm not very familiar with npm internals.

**Comment by piranna** [comment]
Mostly the fact that npm install the dependencies in a somewhat random order and that each modules subtree has a copy of all its dependencies, that for small modules like ws is not a drama to compile them over and over, but the cross-toolchain spend about 1 hour... :-/

Multi-stage installs will meticulously follow an order for install the modules and making checks everywhere, so one module will not be installed if all its dependencies are not installed firsts, and also will make sure all the preinstall scripts are executed previously to install the depencies and the install and postinstall after them. The flat dependencies will try to create an as flat as possible node_modules directory by default instead of having each module its own copy of its dependencies, wasting less hard disk and reducing install times (for example, the cross-compiler will be installed only once :-) ). These features are currently availables on the muti-stage branch of npm and will be enabled by default on npm 3.

If you are interested, you can take a look to my cross-compiler at https://github.com/NodeOS/NodeOS/tree/master/node_modules/nodeos-barebones/node_modules/nodeos-cross-toolchain, and as usual, pull-requests are welcome :-)

**Comment by RSATom** [comment]
It seems I understand, thank you for explaining.

About pull requests - ok, if I will have one :)

**Comment by piranna** [comment]
Thank you ;-)

**Comment by unbornchikken** [comment]
@RSATom yes, I'm thinking about it as a separate module when it gets added to the application as a dependency anywhere directly or indirectly all cmake.js based builds will use its deployed toolset. Of course, if there is an already availabled cmake compatible toolset, nothing gets deployed. I think I can put it together for Windows in a few days. For OSX it will be harder though because I ain't got a real Mac, just that hacked shit.

**Comment by RSATom** [comment]
@unbornchikken, what hardware do you have? I have some experience in running different OS X  versions on not native hardware, maybe you could help.

**Comment by unbornchikken** [comment]
@RSATom i5 with a Radeon R9

**Comment by RSATom** [comment]
I5 is good, then you could use http://www.tonymacx86.com/yosemite-desktop-guides/143976-unibeast-install-os-x-yosemite-any-supported-intel-based-pc.html Better setup it on separate HDD/SSD

**Comment by unbornchikken** [comment]
Since I'm busy with [Fire.js](https://github.com/unbornchikken/fire-js), I've decided that I start to implement this if there's gonna be three more upvote or the repo reach hundred starts. (Or Fire.js gets feature complete of course.)

**Comment by Globik** [comment]
I"m on windows 7. Can I use cmake-js with gcc or clang compiler? Fucking visual studio 10 seems does not understand c++11 and c 14.

**Comment by RSATom** [comment]
@Globik, you could use Visual Studio 2013/2015 Community - it support c++11 and free

**Comment by Globik** [comment]
I am not asking for the fucking visual studio 2013/15,  I amasking how to insert clang or gcc into cmakelists.txt file for cmake-js.

**Comment by unbornchikken** [comment]
Please find funcking my answer there: https://github.com/arrayfire/arrayfire-js/issues/6#issuecomment-129318526 :)

**Comment by Globik** [comment]
Yes, I saw your answer. It would be nice when we, windows guys, could use clang compiler also in your cmake-js scripts.

**Comment by unbornchikken** [comment]
That's the plan there.

**Comment by RSATom** [comment]
@Globik, русского человека за версту видно...

**Comment by unbornchikken** [comment]
But PRs are welcome as always. ;)

**Comment by Globik** [comment]
@unbornchikken  what is the module for this PRs? I can't see it on npm site.
@RSATom ну дак, куда только нелегкая не заведет, чтобы что-либо разузнать. К тому в топике верху самом ясно обозначено, что fu***ing Visual Studio есть то, что есть.

**Comment by unbornchikken** [comment]
its just `cmake-js` on the npm

**Comment by etiktin** [comment]
+1. I think it will definitely improve the experience for first time users on Windows. 
Is the plan to support both msbuild and mingw transparently or will you have to fiddle with the configuration?

**Comment by unbornchikken** [comment]
So, there are more than 100 starts actually. I'm considering this as a popular demand, and as soon as I managed to get some spare time, I start to prototype the Windows version.

However, I don't feel that there is anything that needs to be done in non Windows platforms, because if I'm on linux I can write:

```bash
sudo apt-get instal g++
```

On Mac I can write:

```bash
brew install llvm --with-clang --with-asan 
```

And Cmake.js will work as intended. There is no need to do an other package manager that I'm planning to do for this.

**Comment by piranna** [comment]
It would be a good thing to have a C compiler as a npm package, maybe with
node-pre-gyp, but ideally written in Javascript.

**Comment by Frix-x** [comment]
Hi, I would love to use MinGW g++ compiler on windows in place of the MSVC toolchain. What is the state of the project today ? Is it still in the roadmap ?

**Comment by janakg** [comment]
We would like to explore this. MinGW g++ compiler on windows. Can you help us with where to start for this (a high-level overview) and how to set up a dev environment for this project.

**Comment by Animeshz** [comment]
Hi, was there any updates on this? 👀
