### ISSUE TITLE
Checksum error when building

### ISSUE THREAD

**Issue by kenr** [unbornchikken/cmake-js#18]
On Windows 7 Enterprise (x64) with Node.js 0.12.4 (ia32), when building a native extension the following error occur:

**cmake-js -D**
info DIST Downloading distribution files.
http DIST       - http://nodejs.org/dist/v0.12.4/SHASUMS256.txt
http DIST       - http://nodejs.org/dist/v0.12.4/win-x86/node.lib
http DIST       - http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
**ERR! OMG SHA sum of file 'win-x86/node.lib' mismatch!**
**ERR! OMG SHA sum of file 'win-x86/node.lib' mismatch!**
Unhandled rejection Error: SHA sum of file 'win-x86/node.lib' mismatch!

Any idea on what may be wrong ?

**Comment by unbornchikken** [comment]
It tries to load the library with the url scheme used at io.js' distribution server. Are you using the latest version? If you are, then I think its because the isiojs module that CMake.js uses to detect if the actual runtime is io.js or not confused about 0.12.4. It misdetect it as io.js somehow. I'll take a look into this.

**Comment by kenr** [comment]
It seems the URL http://nodejs.org/dist/v0.12.4/win-x86/node.lib is a 404...
The version of cmake-js I'm using is 1.0.0.

**Comment by unbornchikken** [comment]
I've just tried Node.js 0.12.4 x86 on Win 7, and CMake.js 1.0.0 builds my module flawlessly. Did you update the global or the local (the one in node_modules folder) CMake.js to 1.0?

**Comment by unbornchikken** [comment]
I get:
```
info DIST Downloading distribution files.
http DIST       - http://nodejs.org/dist/v0.12.4/SHASUMS256.txt
http DIST       - http://nodejs.org/dist/v0.12.4/node.lib
http DIST       - http://nodejs.org/dist/v0.12.4/node-v0.12.4.tar.gz
```

**Comment by unbornchikken** [comment]
I can confirm the this issue exists in pre 1.0.0 version of CMake.js and it got fixed in 1.0.0 for sure, I've just tried both with 0.12.4 x86. I think that you're trying to compile it with global cmake-js executable which is not at version 1.0. Please update, and the issue begone.

**Comment by kenr** [comment]
I updated only the local one, after updating the global one and it works. Sorry for this, I'm new to the node-js/npm galaxy. Thank you @unbornchikken .

**Comment by unbornchikken** [comment]
np
