### ISSUE TITLE
using --arch on windows does nothing

### ISSUE THREAD

**Issue by johnsusi** [unbornchikken/cmake-js#19]
Running `cmake-js rebuild --runtime=electron --runtime-version=0.28.3 --arch=x64` 
On a 32-bit windows machine NODE_ARCH=ia32 and on a 64 bit machine NODE_ARCH=x64.

Looks like a typo in bin/cmake-js at line 123

`    arch: argv.A` should be `arch: argv.a`

**Comment by unbornchikken** [comment]
Yup, good catch, thank you. Fixed in 1.0.1.
