### ISSUE TITLE
Developing with CLion

### ISSUE THREAD

**Issue by ReneHollander** [unbornchikken/cmake-js#23]
I am wondering what has to be done to let CLion compile the addon from within the IDE. Currently I am just executing cmake-js rebuild from the command line, but in CLion everything associated with nan is red and I can't use the debugger CLion provides. It is not possible, at least as far as I know, to execute a custom command to build the project.

I tried to add CMAKE_JS_INC vatiable to the CMake project settings enviroment variables without success. I also tried to configure a external tool to build the project with, but that did not work either.

**Comment by ReneHollander** [comment]
As a workaround I use the output of `cmake-js --print-configuration` and set the variables from within CMake:
```cmake
cmake_minimum_required(VERSION 3.2.2)

function(PARSE_CMAKEJS_PROPERTIES)
  function(GET_VARIABLE INPUT_STRING VARIABLE_TO_SELECT OUTPUT_VARIABLE)
    set(SEARCH_STRING "${VARIABLE_TO_SELECT}=\"")
    string(LENGTH "${SEARCH_STRING}" SEARCH_STRING_LENGTH)
    string(LENGTH "${INPUT_STRING}" INPUT_STRING_LENGTH)

    string(FIND "${INPUT_STRING}" "${VARIABLE_TO_SELECT}=\"" SEARCH_STRING_INDEX)

    math(EXPR SEARCH_STRING_INDEX "${SEARCH_STRING_INDEX}+${SEARCH_STRING_LENGTH}")

    string(SUBSTRING "${INPUT_STRING}" ${SEARCH_STRING_INDEX} ${INPUT_STRING_LENGTH} AFTER_SEARCH_STRING)
    string(FIND "${AFTER_SEARCH_STRING}" "\"" QUOTE_INDEX)
    string(SUBSTRING "${AFTER_SEARCH_STRING}" "0" "${QUOTE_INDEX}" RESULT_STRING)
    set("${OUTPUT_VARIABLE}" "${RESULT_STRING}" PARENT_SCOPE)
  endfunction(GET_VARIABLE)

  string(TOLOWER "${CMAKE_BUILD_TYPE}" CMAKE_BUILD_TYPE_LOWER)
  if (CMAKE_BUILD_TYPE_LOWER STREQUAL "debug")
    exec_program(./node_modules/.bin/cmake-js ${CMAKE_CURRENT_SOURCE_DIR}
                 ARGS print-configure --debug
                 OUTPUT_VARIABLE CMAKE_JS_OUTPUT
    )
  else()
    exec_program(./node_modules/.bin/cmake-js ${CMAKE_CURRENT_SOURCE_DIR}
                 ARGS print-configure
                 OUTPUT_VARIABLE CMAKE_JS_OUTPUT
    )
  endif ()

  get_variable("${CMAKE_JS_OUTPUT}" "CMAKE_JS_INC" CMAKE_JS_INC)
  set(CMAKE_JS_INC "${CMAKE_JS_INC}" PARENT_SCOPE)

  get_variable("${CMAKE_JS_OUTPUT}" "CMAKE_LIBRARY_OUTPUT_DIRECTORY" CMAKE_LIBRARY_OUTPUT_DIRECTORY)
  set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}" PARENT_SCOPE)

endfunction(PARSE_CMAKEJS_PROPERTIES)

project(rep0st)

parse_cmakejs_properties()

include_directories("${CMAKE_JS_INC}")
file(GLOB SOURCE_FILES "src/*.cc" "src/*.h")
add_library(${PROJECT_NAME} SHARED ${SOURCE_FILES})
set_target_properties(${PROJECT_NAME} PROPERTIES PREFIX "" SUFFIX ".node")
target_link_libraries(${PROJECT_NAME} ${CMAKE_JS_LIB})
```

It is messy and only covers CMAKE_JS_INC and the library output path but it works like a charm.

**Comment by unbornchikken** [comment]
Hi,

I ain't got the time to test CMake.js with CLion yet. There should be somwhere an option to define CMake variables, or CMake commandline, like with Qt Creator or Kdevelop. There you hafta paste options that `cmake-js print-configure` gives.

I cannot imagine a CMake compatible IDE that gives no options to define CMake variables for the debug process.

**Comment by ReneHollander** [comment]
I was only able to set enviroment variables that supposedly should get passed to CLion, but it didn't work. I will for now keep my custom `CMakeLists.txt` because it works. The only thing to mention is that there is no Windows compatibility. For that to work the `exec_programm` call has to be adjusted.

**Comment by unbornchikken** [comment]
I see. However custom CMake arguments gotta be supported by every IDE that calls themselves as "CMake compatible". Every other IDE that I know supports that some way, even Qt Creator does, that is built around its own build system, CMake is just an icing on the cake. This issue is related to CLion, not CMake.js. I cannot do anything that makes CLion behave as intended.

**Comment by corymickelson** [comment]
@ReneHollander  Thank you so much for the parse-cmakejs-properties() that saved me a good deal of frustration.

**Comment by gdianaty** [comment]
I know this issue ticket is over five years old at this point, but I wrote a new version of it that supports Windows and works to build CMake.js projects with Visaul Studio, CLion and just about anything else. You can find it [here](https://gist.github.com/gdianaty/33c3190a217cd188ea43cd4b06618ba9).

**Comment by unbornchikken** [comment]
PRs would be much appreciated as always. ;)
