### ISSUE TITLE
Building with Electron 0.32.1 failed with "incorrect header check" error

### ISSUE THREAD

**Issue by hankbao** [unbornchikken/cmake-js#24]
Building my addon with cmake-js throws "incorrect header check" error. ~~This problem may caused by electron side though I'm not certain. So I opened an issue here.~~

``` 
$ cmake-js rebuild -r electron -v 0.32.1 -a ia32 -l=silly

...
info DIST Downloading distribution files.
http DIST 	- http://atom.io/download/atom-shell/v0.32.1/node-v0.32.1.tar.gz
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: incorrect header check
    at Zlib._handle.onerror (zlib.js:366:17)
```

**Comment by hankbao** [comment]
Downloading "http://atom.io/download/atom-shell/v0.32.1/node-v0.32.1.tar.gz" manually is OK and it can be extracted with no problem.

**Comment by hankbao** [comment]
Manually puting extracted contents into `~/.cmake-js/electron-ia32/v0.32.1` then running rebuild succeeded.

**Comment by unbornchikken** [comment]
Ain't reproducible. I can build my modules with the mentioned commandline without problems:

```bash
info DIST Downloading distribution files.
http DIST       - http://atom.io/download/atom-shell/v0.32.1/node-v0.32.1.tar.gz
info CMD CLEAN
info RUN cmake -E remove_directory "/home/gabor/git/cmake-js-tut-01-module/build"
info CMD CONFIGURE
info RUN cmake "/home/gabor/git/cmake-js-tut-01-module" --no-warn-unused-cli -GNinja -DCMAKE_BUILD_TYPE="Release" -DCMAKE_LIBRARY_OUTPUT_DIRECTORY="/home/gabor/git/cmake-js-tut-01-module/build/Release" -DCMAKE_JS_INC="/home/gabor/.cmake-js/electron-ia32/v0.32.1/src;/home/gabor/.cmake-js/electron-ia32/v0.32.1/deps/v8/include;/home/gabor/.cmake-js/electron-ia32/v0.32.1/deps/uv/include;/home/gabor/git/cmake-js-tut-01-module/node_modules/nan" -DNODE_RUNTIME="electron" -DNODE_RUNTIMEVERSION="0.32.1" -DNODE_ARCH="ia32" -DCMAKE_CXX_FLAGS="-std=c++11" -DAF_PATH="/home/gabor/dev/ArrayFire-3.0"
```

I'm using CMake.js latest and Node 4, but I've tested it with io.js latest too, and it worked.

**Comment by hankbao** [comment]
I've tested and failed again with cmake-js 1.0.2 and node v4 in another network environment. Not sure if this would be related to the complex network conditions in China.

**Comment by hankbao** [comment]
It turns out to be due to amazon s3 being blocked by GFW. Sorry for bothering here.

**Comment by unbornchikken** [comment]
np i feel yer pain :(
