### ISSUE TITLE
Regression: build against nw.js v0.12.3 failed with cmake-js v1.1.0

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#25]
https://ci.appveyor.com/project/RSATom/webchimera-js/build/0.0.0.146/job/xjkvv4iyc0l8jgal
it seems it's something wrong with include search path:
> c:\projects\webchimera-js\src\JsVlcAudio.h(5): fatal error C1083: Cannot open include file: 'v8.h': No such file or directory [C:\projects\webchimera-js\build\WebChimera.js.vcxproj]

but it builds fine if I force use cmake-js v1.0.2

**Comment by unbornchikken** [comment]
Indeed. Moment.

**Comment by unbornchikken** [comment]
Please try with 1.1.1.

**Comment by RSATom** [comment]
Yes, now it works fine:
https://travis-ci.org/RSATom/WebChimera.js/builds/85676477
https://ci.appveyor.com/project/RSATom/webchimera-js/build/0.0.0.149
Thanks!

**Comment by unbornchikken** [comment]
Sorry about that. May I use a WC.js' fork for regression testing of the new versions?

**Comment by RSATom** [comment]
"Shit happens" - so don't worry :) And yes, you are free to use `wcjs` as you like.
