### ISSUE TITLE
cmake-js v2.0.0 print-configure does not work

### ISSUE THREAD

**Issue by bfrancojr** [unbornchikken/cmake-js#27]
Hi,

After update cmake-js from v1.1.1 to v2.0.0, I'm getting the following output:

$ cmake-js print-configure
info CFG Applying CMake.js config from root package.json:
info CFG {"runtime":"node","runtimeVersion":"0.12.7","arch":"x64"}
undefined

Any idea?

**Comment by unbornchikken** [comment]
I'll look into it tonight. Expect a fix arrive on tomorrow morning.

**Comment by bfrancojr** [comment]
Thank you!

**Comment by unbornchikken** [comment]
Fixed as of 2.0.2.
