### ISSUE TITLE
[question] is it possible build for ia32 on x64 linux?

### ISSUE THREAD

**Issue by RSATom** [unbornchikken/cmake-js#28]
I need to do it inside Travis-CI. Is it possible, how do you think?

**Comment by unbornchikken** [comment]
Hi, if I remember correctly, Ubuntu doesn't come with i386 runtime and tools, but that's installable with apt-get. Then you gotta install i386 build-essentials, then node i386. If you run your build with that, then it builds ia32 automatically. Well, that's the theory actually. But by my understanding that should work that way.

**Comment by unbornchikken** [comment]
Or maybe there is an option for Travis to use i386 container. Then you'll have tools for ia32 instantly.

**Comment by RSATom** [comment]
Understand, thanks for explaining. I'll try.
