### ISSUE TITLE
CMake-js is not respecting CC and CXX env vars

### ISSUE THREAD

**Issue by bfrancojr** [unbornchikken/cmake-js#29]
Hi,

I have integrated a CMake based project with a cmake-js based one as a sub-project but cmake-js is not respecting my compiler preference informed through CC and CXX environment vars.
CMake-js has clang (at least under OSX) as its default compiler. I'm aware that cmake-js has -g option to switch to gcc instead but -g option is not a CMake supported feature, so it is not trivial to have cmake and cmake-js together using the same compiler seamlessly.
The main issue I'm facing now, as you may guess, is to have the nodejs native module which depends on a shared library built by the main project being compiled by two different compilers.

I would like to know your thoughts about this issue.

Thanks!

**Comment by unbornchikken** [comment]
So, you're basically requesting a new option for respecting environment variables instead of clang or gnu, right?

**Comment by bfrancojr** [comment]
Yes, it could be implemented like that.
But in my opinion, if I may, cmake-js should behave like any other cmake project, having as default compiler what is indicated by CC/CXX vars, if no arguments is passed in the command line.

**Comment by unbornchikken** [comment]
Ok, that makes sense. I'll promote clang behind an option and by default, I let cmake use that it want. Would that satisfy your needs?

**Comment by bfrancojr** [comment]
Yes, it'll work perfectly.

Thank you again!

**Comment by unbornchikken** [comment]
2.1.0 tagged, see --help for details. Without specifying any prefer-.. option, default compiler's gonna be selected.
