### ISSUE TITLE
[Doc] Update to tutorial 1

### ISSUE THREAD

**Issue by MajorBreakfast** [unbornchikken/cmake-js#30]
I've read through the wiki's tutorial 1 and made some adjustments:
- Fixed some mistakes
- Removed repetitive passages
- Updated `CMakeLists.txt` to use `target_include_directories()`

https://gist.github.com/MajorBreakfast/b92c82ad1701e604f788

Note: I can't provide a PR unfortunately because github doesn't support PRs for wiki repos.

BTW cmake-js worked great for me so far (on all three platforms). So, thanks for that!

**Comment by unbornchikken** [comment]
Hi,
Thanks for contribute.
I've opened up the wiki, so you can push your changes with GIT from now on:
https://github.com/unbornchikken/cmake-js.wiki.git
BR,unbornchikken

Date: Wed, 11 Nov 2015 02:02:29 -0800

**Comment by unbornchikken** [comment]
Updated, thanks!

**Comment by MajorBreakfast** [comment]
Nice. Thx. :)
